### ISSUE TITLE
UI (Check comments for checklist)

### ISSUE THREAD

**Issue by TWilson2017** [TWilson2017/Vendor-App#19]
- [ ] UI for store manager & make sure the UI is formatted correctly (run emulator and confirm)
- [ ] UI for adding a store
- [ ] UI for listing items in a store
- [ ] UI for adding an item to a store
- [ ] Add correct code to AndroidManifest.XML for UI
- [ ] Don't give the buttons the same name
- [ ] UI for Store Manager to Register and Register a Store
- [ ] UI for Vendor to register store & field to add store manager
- [ ] Connect Buttons (Java Code)
